import { activeCellState } from "../../Types/activeCellState";

const blocks = [
  [
    { x: 0, y: 0 },
    { x: 0, y: 1 },
    { x: 0, y: 2 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 1, y: 2 },
    { x: 2, y: 0 },
    { x: 2, y: 1 },
    { x: 2, y: 2 },
  ],
  [
    { x: 0, y: 3 },
    { x: 0, y: 4 },
    { x: 0, y: 5 },
    { x: 1, y: 3 },
    { x: 1, y: 4 },
    { x: 1, y: 5 },
    { x: 2, y: 3 },
    { x: 2, y: 4 },
    { x: 2, y: 5 },
  ],
  [
    { x: 0, y: 6 },
    { x: 0, y: 7 },
    { x: 0, y: 8 },
    { x: 1, y: 6 },
    { x: 1, y: 7 },
    { x: 1, y: 8 },
    { x: 2, y: 6 },
    { x: 2, y: 7 },
    { x: 2, y: 8 },
  ],
  [
    { x: 3, y: 0 },
    { x: 3, y: 1 },
    { x: 3, y: 2 },
    { x: 4, y: 0 },
    { x: 4, y: 1 },
    { x: 4, y: 2 },
    { x: 5, y: 0 },
    { x: 5, y: 1 },
    { x: 5, y: 2 },
  ],
  [
    { x: 3, y: 3 },
    { x: 3, y: 4 },
    { x: 3, y: 5 },
    { x: 4, y: 3 },
    { x: 4, y: 4 },
    { x: 4, y: 5 },
    { x: 5, y: 3 },
    { x: 5, y: 4 },
    { x: 5, y: 5 },
  ],
  [
    { x: 3, y: 6 },
    { x: 3, y: 7 },
    { x: 3, y: 8 },
    { x: 4, y: 6 },
    { x: 4, y: 7 },
    { x: 4, y: 8 },
    { x: 5, y: 6 },
    { x: 5, y: 7 },
    { x: 5, y: 8 },
  ],
  [
    { x: 6, y: 0 },
    { x: 6, y: 1 },
    { x: 6, y: 2 },
    { x: 7, y: 0 },
    { x: 7, y: 1 },
    { x: 7, y: 2 },
    { x: 8, y: 0 },
    { x: 8, y: 1 },
    { x: 8, y: 2 },
  ],
  [
    { x: 6, y: 3 },
    { x: 6, y: 4 },
    { x: 6, y: 5 },
    { x: 7, y: 3 },
    { x: 7, y: 4 },
    { x: 7, y: 5 },
    { x: 8, y: 3 },
    { x: 8, y: 4 },
    { x: 8, y: 5 },
  ],
  [
    { x: 6, y: 6 },
    { x: 6, y: 7 },
    { x: 6, y: 8 },
    { x: 7, y: 6 },
    { x: 7, y: 7 },
    { x: 7, y: 8 },
    { x: 8, y: 6 },
    { x: 8, y: 7 },
    { x: 8, y: 8 },
  ],
];

const blocksAssociatedWithCells = {
  "cell00": blocks[0],
  "cell01": blocks[0],
  "cell02": blocks[0],
  "cell10": blocks[0],
  "cell11": blocks[0],
  "cell12": blocks[0],
  "cell20": blocks[0],
  "cell21": blocks[0],
  "cell22": blocks[0],

    "cell03": blocks[1],
    "cell04": blocks[1],
    "cell05": blocks[1],
    "cell13": blocks[1],
    "cell14": blocks[1],
    "cell15": blocks[1],
    "cell23": blocks[1],
    "cell24": blocks[1],
    "cell25": blocks[1],

    "cell06": blocks[2],
    "cell07": blocks[2],
    "cell08": blocks[2],
    "cell16": blocks[2],
    "cell17": blocks[2],
    "cell18": blocks[2],
    "cell26": blocks[2],
    "cell27": blocks[2],
    "cell28": blocks[2],

    "cell30": blocks[3],
    "cell31": blocks[3],
    "cell32": blocks[3],
    "cell40": blocks[3],
    "cell41": blocks[3],
    "cell42": blocks[3],
    "cell50": blocks[3],
    "cell51": blocks[3],
    "cell52": blocks[3],

    "cell33": blocks[4],
    "cell34": blocks[4],
    "cell35": blocks[4],
    "cell43": blocks[4],
    "cell44": blocks[4],
    "cell45": blocks[4],
    "cell53": blocks[4],
    "cell54": blocks[4],
    "cell55": blocks[4],

    "cell36": blocks[5],
    "cell37": blocks[5],
    "cell38": blocks[5],
    "cell46": blocks[5],
    "cell47": blocks[5],
    "cell48": blocks[5],
    "cell56": blocks[5],
    "cell57": blocks[5],
    "cell58": blocks[5],

    "cell60": blocks[6],
    "cell61": blocks[6],
    "cell62": blocks[6],
    "cell70": blocks[6],
    "cell71": blocks[6],
    "cell72": blocks[6],
    "cell80": blocks[6],
    "cell81": blocks[6],
    "cell82": blocks[6],

    "cell63": blocks[7],
    "cell64": blocks[7],
    "cell65": blocks[7],
    "cell73": blocks[7],
    "cell74": blocks[7],
    "cell75": blocks[7],
    "cell83": blocks[7],
    "cell84": blocks[7],
    "cell85": blocks[7],

    "cell66": blocks[8],
    "cell67": blocks[8],
    "cell68": blocks[8],
    "cell76": blocks[8],
    "cell77": blocks[8],
    "cell78": blocks[8],
    "cell86": blocks[8],
    "cell87": blocks[8],
    "cell88": blocks[8],
};
export const inTheSameBlock = (
  _activeCell: activeCellState,
  rowIndex: number,
  colIndex: number
): boolean => {
  const activeCell = { x: _activeCell.x, y: _activeCell.y };
  const activeCellXString = activeCell.x === null ? '' : activeCell.x.toString();
  const activeCellYString = activeCell.y === null ? '' : activeCell.y.toString();
  const activeCellIndexString = `cell${activeCellXString}${activeCellYString}`
  const givenCellIndexString = `cell${rowIndex}${colIndex}`

  return (blocksAssociatedWithCells as any)[activeCellIndexString] === (blocksAssociatedWithCells as any)[givenCellIndexString];
};